"""
Reflection Engine for Chhaya.
Analyzes agent performance and proposes blueprint improvements.
"""

import json
from typing import Any, Dict
import structlog

from chhaya_v1.domain.models import AgentBlueprint, ModelTier
from chhaya_v1.interfaces.llm_provider import LLMProvider
from chhaya_v1.core.agent_registry import AgentRegistry
from chhaya_v1.core.tool_registry import ToolRegistry
from chhaya_v1.interfaces.event_bus import EventBus

logger = structlog.get_logger(__name__)


class ReflectionEngine:
    """
    Grades completed runs and proposes new versions of AgentBlueprints.
    """

    def __init__(
        self,
        llm_provider: LLMProvider,
        agent_registry: AgentRegistry,
        tool_registry: ToolRegistry,
        event_bus: EventBus,
    ):
        self.llm = llm_provider
        self.registry = agent_registry
        self.tools = tool_registry
        self.event_bus = event_bus

    def _build_reflection_prompt(self, blueprint: AgentBlueprint, task: str, result: str, feedback: str) -> str:
        """
        Constructs the prompt for the 14b reasoning model to critique and update the blueprint.
        """
        available_tools = [tool.name for tool in self.tools.get_all_tools()]

        prompt = f"""You are the Chhaya Reflection Engine. Your job is to improve an existing AI Agent.

Current Agent Details:
- Name: {blueprint.name}
- Role: {blueprint.role}
- System Prompt: {blueprint.system_prompt}
- Current Tools: {blueprint.tools}

Run Context:
- The agent was given this task: "{task}"
- The agent produced this result: "{result}"
- Feedback/Error context: "{feedback}"

Available tools in the system you can add/swap: {available_tools}

Based on the feedback and result, propose an updated AgentBlueprint.
You may modify the 'system_prompt' to prevent future errors, or change the 'tools' list if different capabilities are needed.
DO NOT change the 'name' or 'role'.

Output ONLY a raw JSON object matching this schema perfectly (do not use markdown blocks):
{{
    "system_prompt": "The new, improved system prompt.",
    "tools": ["tool_1", "tool_2"]
}}
"""
        return prompt

    def reflect_and_improve(self, blueprint_name: str, task: str, result: str, feedback: str) -> AgentBlueprint:
        """
        Analyzes a run and proposes a new version of the blueprint.

        Args:
            blueprint_name: The name of the agent to improve.
            task: The task that was executed.
            result: The output generated by the agent.
            feedback: Any external feedback or error logs from the run.

        Returns:
            The newly created, proposed (version incremented) AgentBlueprint.

        Raises:
            ValueError: If the blueprint is not found or LLM generation fails.
        """
        logger.info("Starting reflection", agent_name=blueprint_name)

        original_blueprint = self.registry.load_blueprint(blueprint_name)
        if not original_blueprint:
            raise ValueError(f"Cannot reflect on unknown agent: {blueprint_name}")

        self.event_bus.publish("reflection_started", {"agent_name": blueprint_name})

        prompt = self._build_reflection_prompt(original_blueprint, task, result, feedback)

        try:
            # Force reasoning tier for reflection tasks
            response_text = self.llm.generate(
                prompt=prompt,
                model_tier=ModelTier.REASONING_14B.value,
                format="json"
            )

            # Clean up markdown if necessary
            response_text = response_text.strip()
            if response_text.startswith("```json"):
                response_text = response_text.strip("`").removeprefix("json").strip()

            updates: Dict[str, Any] = json.loads(response_text)

            # Construct the new blueprint
            new_data = original_blueprint.model_dump()

            # Apply only authorized updates
            if "system_prompt" in updates:
                new_data["system_prompt"] = updates["system_prompt"]
            if "tools" in updates:
                new_data["tools"] = updates["tools"]

            # Increment version
            new_data["version"] = original_blueprint.version + 1

            new_blueprint = AgentBlueprint(**new_data)

            # Save the new version
            self.registry.save_blueprint(new_blueprint)

            self.event_bus.publish("reflection_completed", {
                "agent_name": new_blueprint.name,
                "old_version": original_blueprint.version,
                "new_version": new_blueprint.version
            })

            logger.info("Reflection complete, new version proposed",
                        agent_name=new_blueprint.name,
                        version=new_blueprint.version)

            return new_blueprint

        except json.JSONDecodeError as e:
            logger.error("Reflection failed to parse LLM JSON", error=str(e), response=response_text)
            self.event_bus.publish("reflection_failed", {"error": "Invalid JSON generated"})
            raise ValueError(f"Failed to parse reflection updates: {e}") from e

        except Exception as e:
            logger.error("Reflection encountered an error", error=str(e))
            self.event_bus.publish("reflection_failed", {"error": str(e)})
            raise
